# Interface design for ISP_2 Router
router_interfaces:
  - name: Ethernet0/1
    description: "Link to R3"
    ipv4: 198.51.100.6/30
  - name: Ethernet0/2
    description: "Link to INET"
    ipv4: 203.0.113.6/30
  - name: lo0
    description: "Loopback 0"
    ipv4: 6.6.6.6/32