# Interface design for R3
router_interfaces:
  - name: Ethernet0/1
    description: "Link to Router 2"
    ipv4: 10.1.1.1/24
  - name: Ethernet0/2
    description: "Link to ISP_1"
    ipv4: 198.51.100.1/30
  - name: Ethernet0/3
    description: "Link to ISP_2"
    ipv4: 198.51.100.5/30
  - name: lo0
    description: "Loopback 0"
    ipv4: 3.3.3.3/32