# Interface design for ISP_1 Router
router_interfaces:
  - name: Ethernet0/1
    description: "Link to R3"
    ipv4: 198.51.100.2/30
  - name: Ethernet0/2
    description: "Link to INET"
    ipv4: 203.0.113.1/30
  - name: lo0
    description: "Loopback 0"
    ipv4: 4.4.4.4/32